### Importing Libraries

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from colorama import Fore

# Preprocessing Essentials
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline, Pipeline

# Regressors
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR

# Evaluation Metrics
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [2]:
os.listdir( '../data/preprocessed data' )

['pre-processed_data.csv']

In [3]:
df = pd.read_csv( '../data/preprocessed data/pre-processed_data.csv' )

In [4]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
13152,male,Bachelor of Science,5.44,91.1,no,4.9,0,coaching,1,1,66.1,5

## Split features into X & y

In [5]:
X = df.drop( columns = 'exam_score' )
y = df['exam_score']

In [6]:
X.shape

(20000, 11)

## Split into training & testing

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [8]:
X_train

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,course_diff
5894,other,Bachelor of Commerce,6.87,57.1,no,9.0,2,group study,0,2,2
3728,other,Bachelor of Arts,6.91,54.8,yes,9.1,2,mixed,1,2,1
8958,other,Bachelor of Arts,5.45,99.4,yes,7.6,1,group study,1,1,1
7671,other,Bachelor of Arts,4.73,47.6,yes,7.0,0,group study,2,1,1
5999,female,Bachelor of Computer Applications,3.81,78.6,yes,7.8,2,group study,2,1,4
...,...,...,...,...,...,...,...,...,...,...,...
11284,female,Bachelor of Commerce,7.36,98.8,yes,7.1,0,mixed,1,2,2
11964,male,Bachelor of Business Administration,5.83,99.0,yes,9.6,0,self-study,2,0,3
5390,male,Bachelor of Arts,1.49,80.1,yes,7.1,2,mixed,1,1,1
860,male,Bachelor of Computer Applications,0.28,52.1,yes,7.1,2,online videos,2,1,4
15795,male,Bachelor of Science,0.59,67.6,no,9.1,2,coaching,0,0,5

# Model Selection

## Getting Your Preprocssing Pipeline Ready !

In [9]:
df.columns

Index(['gender', 'course', 'study_hours', 'class_attendance',
       'internet_access', 'sleep_hours', 'sleep_quality', 'study_method',
       'facility_rating', 'exam_difficulty', 'exam_score', 'course_diff'],
      dtype='object')

In [10]:
preprocessing_step = ColumnTransformer([
    ( 'One-Hot Encoding', OneHotEncoder(), [ 'gender', 'course', 'internet_access', 'study_method' ] ),
    
],  remainder= 'passthrough')
preprocessing_step

ColumnTransformer(remainder='passthrough',
                  transformers=[('One-Hot Encoding', OneHotEncoder(),
                                 ['gender', 'course', 'internet_access',
                                  'study_method'])])

In [11]:
knn_model = KNeighborsRegressor( n_neighbors= 7 )

In [12]:
knn_pipeline = Pipeline([
    ( 'One-Hot encoding', preprocessing_step),
    ( 'model', knn_model )
])
knn_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', KNeighborsRegressor(n_neighbors=7))])

#### Define a function to quickly evaluate your regressor !

In [13]:
def evaluate_regressor( model, model_name: str ,X_train, X_test, y_train, y_test  ) :
    
    print( 'Training.........' + '\n' )
    
    print( model_name + ':' )
    print( '-'*20 )
    
    model.fit( X_train, y_train ) # Training !
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict( X_test )

    print(  )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print(  )

    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )

## Pre-Processing

In [14]:
knn_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', KNeighborsRegressor(n_neighbors=7))])

In [15]:
knn_pipeline.fit( X_train, y_train )

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', KNeighborsRegressor(n_neighbors=7))])

<hr>

### MAE ( Mean Absolute Error ) ->  Look on the Avg. Error
### MSE ( Mean Squared Error )  ->  Triggers if there is high residuals (differences)
### RMSE ( Root Mean Squared Error ) -> Error between MAE & MSE
<hr>

### Calc. Cross Validation Score

In [16]:
cross_val_score( knn_pipeline, X_train, y_train, cv= 4, scoring='neg_mean_squared_error' ).mean()

np.float64(-128.28051264536097)

## Testing GridSearchCV on KNN Model

In [17]:
knn_model = KNeighborsRegressor(  )

In [18]:
gs_knn =  GridSearchCV(
    estimator= knn_pipeline,
    param_grid= { 'model__n_neighbors' : [ 2, 3, 4, 5, 6, 7 ] }
)

In [19]:
gs_knn.fit( X_train, y_train )

GridSearchCV(estimator=Pipeline(steps=[('One-Hot encoding',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('One-Hot '
                                                                         'Encoding',
                                                                         OneHotEncoder(),
                                                                         ['gender',
                                                                          'course',
                                                                          'internet_access',
                                                                          'study_method'])])),
                                       ('model',
                                        KNeighborsRegressor(n_neighbors=7))]),
             param_grid={'model__n_neighbors': [2, 3, 4, 5, 6, 7]})

In [20]:
print( f'Best value for knn n_neighbors: { gs_knn.best_params_ }' )

Best value for knn n_neighbors: {'model__n_neighbors': 7}

<hr>

# [2] Linear Regression

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lin_reg_model = LinearRegression()

In [23]:
lin_reg_pipeline = Pipeline([
    ( 'One-Hot encoding', preprocessing_step),
    ( 'model', lin_reg_model )
])
lin_reg_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', LinearRegression())])

In [24]:
lin_reg_pipeline.fit( X_train, y_train )

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', LinearRegression())])

In [25]:
y_pred_train_lr = lin_reg_pipeline.predict( X_train )
y_pred_test_lr = lin_reg_pipeline.predict( X_test )

### How linear regression works with multiple features ?

## ----> Y = b + p1x1 + p2x2 + p3x3 + p4x4 +  .......... p24x24

In [26]:
evaluate_regressor( lin_reg_pipeline, 'Linear Regression', X_train, X_test, y_train, y_test )

Training.........

Linear Regression:
--------------------

Mean Absolute Error of training : 7.849729059806821
Mean Squared Error of training : 95.82557389270735
Root Mean Squared Error of Training : 9.789053779232564

Mean Absolute Error of Testing : 7.86201359973348
Mean Squared Error of Testing : 95.46814634090127
Root Mean Squared Error of Testing : 9.770780231941627

## [3] Linear Regression with regularization L1 ( Lasso )

In [27]:
lin_reg_L1 = Lasso( alpha = 0.2 )

In [28]:
lin_reg_L1_pipeline = Pipeline([
    ( 'One-Hot encoding', preprocessing_step),
    ( 'model', lin_reg_L1 )
])
lin_reg_L1_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', Lasso(alpha=0.2))])

In [29]:
evaluate_regressor( lin_reg_L1_pipeline, 'Linear Regression with REGULARIZATION ( L1 )', X_train, X_test, y_train, y_test  )

Training.........

Linear Regression with REGULARIZATION ( L1 ):
--------------------

Mean Absolute Error of training : 7.896830655004453
Mean Squared Error of training : 96.7851698104928
Root Mean Squared Error of Training : 9.837945405952038

Mean Absolute Error of Testing : 7.918296523622174
Mean Squared Error of Testing : 96.60238798040643
Root Mean Squared Error of Testing : 9.8286513815684

## [4] Linear Regression with regularization L2 ( Ridge )

In [30]:
line_reg_R2 = Ridge(  )

In [31]:
line_reg_R2_pipeline = Pipeline([
    ( 'One-Hot encoding', preprocessing_step),
    ( 'model', line_reg_R2 )
])
line_reg_R2_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', Ridge())])

In [32]:
evaluate_regressor( line_reg_R2_pipeline, 'Linear Regression with REGULARIZATION ( L2 )', X_train, X_test, y_train, y_test  )

Training.........

Linear Regression with REGULARIZATION ( L2 ):
--------------------

Mean Absolute Error of training : 7.849739744732458
Mean Squared Error of training : 95.82557531103602
Root Mean Squared Error of Training : 9.78905385167719

Mean Absolute Error of Testing : 7.862034248342014
Mean Squared Error of Testing : 95.46824428283715
Root Mean Squared Error of Testing : 9.770785243921654

## [5] Support Vector Machine

In [33]:
from sklearn.svm import SVR

In [34]:
svm_regressor = SVR(  )

In [35]:
svm_pipeline = Pipeline([
    ( 'One-Hot encoding', preprocessing_step),
    ( 'model', svm_regressor )
])
svm_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('model', SVR())])

In [36]:
evaluate_regressor( svm_pipeline, 'SVM Without Scaling', X_train, X_test, y_train, y_test  )

Training.........

SVM Without Scaling:
--------------------

Mean Absolute Error of training : 9.628362006255745
Mean Squared Error of training : 142.56961963495658
Root Mean Squared Error of Training : 11.940252075854872

Mean Absolute Error of Testing : 9.809015763770596
Mean Squared Error of Testing : 145.43736840460892
Root Mean Squared Error of Testing : 12.059741639214703

## [6] Support Vector Machine with Scaling

In [37]:
# Insert a new step at index 1 (between Encoding and Scaling)

svm_pipeline.steps.insert( 1, ( 'Scaling', StandardScaler() ) )
svm_pipeline

Pipeline(steps=[('One-Hot encoding',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('One-Hot Encoding',
                                                  OneHotEncoder(),
                                                  ['gender', 'course',
                                                   'internet_access',
                                                   'study_method'])])),
                ('Scaling', StandardScaler()), ('model', SVR())])

### Model Serialization ( Saving ) ( dumping )

In [38]:
evaluate_regressor( svm_pipeline, 'SVM With Scaling', X_train, X_test, y_train, y_test  )

Training.........

SVM With Scaling:
--------------------

Mean Absolute Error of training : 7.764041233121284
Mean Squared Error of training : 95.38082144872725
Root Mean Squared Error of Training : 9.766310534113035

Mean Absolute Error of Testing : 8.026937148942237
Mean Squared Error of Testing : 98.94547004435063
Root Mean Squared Error of Testing : 9.947133760252278

In [39]:
import joblib
joblib.dump( svm_pipeline, '../artifacts/svm_pipeline.pkl' )

['../artifacts/svm_pipeline.pkl']

### Try Fine-Tuning

### if kernel == 'poly' --> higher degree -> pruning overfitting

#### if gamma small -> try not to fit all data -> high error -> underfitting
#### if gamma high -> FIT ALL THE DATA AS POSSIBLE -> low error -> overfitting

<hr>

## C
#### C -> regularization parameter
#### High C -> model tries hard to fit all data -> risk overfitting
#### Low C -> model allows erros -> risk underfitting

<hr>