In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv( '../data/feature eng data/feature_eng_data.csv' )

# Encoding Categorical Columns

### * Encoding ordinal columns using Label Encoding

In [3]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
2411,male,Bachelor of Arts,0.55,73.1,yes,7.5,poor,online videos,medium,easy,34.8,1

### 1) columns to label encode :
 'sleep_quality', 'facility_rating', 'exam_difficulty'

In [4]:
df['exam_difficulty'].unique()

array(['hard', 'moderate', 'easy'], dtype=object)

In [5]:
def encode_sleep_quality( df ) :
    df['sleep_quality'] = df['sleep_quality'].map({
        'poor' : 0, 'average' : 1, 'good' : 2
    })
    return df
    
df = encode_sleep_quality( df )

In [6]:
def encode_facility_rating( df ) :
    df['facility_rating'] = df['facility_rating'].map({
        'low' : 0, 'medium' : 1, 'high' : 2
    })
    return df
    
df = encode_facility_rating( df )

In [7]:
def encode_exam_difficulty( df ) :
    df['exam_difficulty'] = df['exam_difficulty'].map({
        'easy' : 0, 'moderate' : 1, 'hard' : 2
    })
    return df
    
df = encode_exam_difficulty( df )

In [8]:
df.sample()

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
5000,other,Bachelor of Computer Applications,1.1,46.3,no,4.5,0,mixed,0,1,37.2,4

In [9]:
df.shape

(20000, 12)

In [12]:
df

,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score,course_diff
0,male,Diploma,2.78,92.9,yes,7.4,0,coaching,0,2,58.9,0
1,other,Bachelor of Computer Applications,3.37,64.8,yes,4.6,1,online videos,1,1,54.8,4
2,male,Bachelor of Science,7.88,76.8,yes,8.5,0,coaching,2,1,90.3,5
3,other,Diploma,0.67,48.4,yes,5.8,1,online videos,0,1,29.7,0
4,female,Diploma,0.89,71.6,yes,9.8,0,coaching,0,1,43.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,other,Bachelor of Business Administration,6.50,71.3,yes,5.0,2,self-study,0,0,86.5,3
19996,male,Bachelor of Commerce,3.71,41.6,no,5.9,1,coaching,1,1,60.9,2
19997,other,Diploma,7.88,68.2,yes,4.6,0,group study,0,0,64.5,0
19998,male,Bachelor of Business Administration,4.60,76.3,no,6.1,2,self-study,1,1,79.0,3
19999,male,Bachelor of Science,7.50,47.9,yes,7.5,0,coaching,1,1,71.0,5

In [13]:
df.to_csv( '../data/preprocessed data/pre-processed_data.csv', index = False )